/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/invite` | `/invite`; params?: Router.UnknownInputParams; } | { pathname: `/story`; params?: Router.UnknownInputParams; } | { pathname: `/story/story/character`; params?: Router.UnknownInputParams; } | { pathname: `/story/story`; params?: Router.UnknownInputParams; } | { pathname: `/story/story/settings`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/invite` | `/invite`; params?: Router.UnknownOutputParams; } | { pathname: `/story`; params?: Router.UnknownOutputParams; } | { pathname: `/story/story/character`; params?: Router.UnknownOutputParams; } | { pathname: `/story/story`; params?: Router.UnknownOutputParams; } | { pathname: `/story/story/settings`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/invite${`?${string}` | `#${string}` | ''}` | `/invite${`?${string}` | `#${string}` | ''}` | `/story${`?${string}` | `#${string}` | ''}` | `/story/story/character${`?${string}` | `#${string}` | ''}` | `/story/story${`?${string}` | `#${string}` | ''}` | `/story/story/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/invite` | `/invite`; params?: Router.UnknownInputParams; } | { pathname: `/story`; params?: Router.UnknownInputParams; } | { pathname: `/story/story/character`; params?: Router.UnknownInputParams; } | { pathname: `/story/story`; params?: Router.UnknownInputParams; } | { pathname: `/story/story/settings`; params?: Router.UnknownInputParams; };
    }
  }
}
